// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmrqomjmelgontrsqhbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtcnFvbWptZWxnb250cnNxaGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NzEwMjAsImV4cCI6MjA3MzA0NzAyMH0.4B7bcY19zBmm--7iAN3lihIhs65PcIXzOKJrQ-WkMBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});