# .github/workflows/deploy.yml
name: Deploy Vite App to GitHub Pages

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true # It's better to cancel previous runs for faster feedback

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Use the latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use the latest version
        with:
          node-version: '20' # Recommend using a current LTS version

      - name: Install dependencies
        run: npm ci # Use 'npm ci' for clean, reproducible installs

      - name: Build project
        run: npm run build # This creates the 'dist' folder

      - name: Setup Pages
        # Configures the repository to deploy to GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        # Uploads the static files from the 'dist' directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # IMPORTANT: Ensure this points to your Vite output folder

      - name: Deploy to GitHub Pages
        id: deployment
        # Deploys the uploaded artifact to your GitHub Pages site
        uses: actions/deploy-pages@v4
